/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAX_H_RPCGEN
#define _MAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intarr {
	int a;
	int b;
};
typedef struct intarr intarr;

#define MAX_PROG 0x23451111
#define MAX__VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MAX_ 1
extern  int * max__1(intarr *, CLIENT *);
extern  int * max__1_svc(intarr *, struct svc_req *);
extern int max_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MAX_ 1
extern  int * max__1();
extern  int * max__1_svc();
extern int max_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intarr (XDR *, intarr*);

#else /* K&R C */
extern bool_t xdr_intarr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAX_H_RPCGEN */
