/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "max.h"

int *max__1_svc(intarr *argp, struct svc_req *rqstp) {
  static int result;
  int a = argp->a, b = argp->b;
  if (a < b)
    result = 1;
  else
    result = 0;
  return (&result);
}
