/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "max.h"

void max_prog_1(char *host, int *a, int n) {
  CLIENT *clnt;
  int *result_1;
  intarr max__1_arg;
  clnt = clnt_create(host, MAX_PROG, MAX__VERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
  max__1_arg.a = a[0];
  for (int i = 1; i < n; ++i) {
    max__1_arg.b = a[i];
    result_1 = max__1(&max__1_arg, clnt);
    if (result_1 == (int *)NULL) {
      clnt_perror(clnt, "call failed:");
    } else {
      if (*result_1) max__1_arg.a = a[i];
    }
  }
  printf("Maximum value of array is: %d\n", max__1_arg.a);
  clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 3) {
    printf("usage: %s <host> [..nums]\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  int *nums = (int *)malloc(sizeof(int) * (argc - 2));
  for (int i = 2; i < argc; ++i) {
    nums[i - 2] = atoi(argv[i]);
  }
  max_prog_1(host, nums, argc - 2);
  exit(0);
}
