/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>

#include "fibonacci.h"
int calculate_fib(int n) {
  if (n <= 1) return n;
  return calculate_fib(n - 1) + calculate_fib(n - 2);
}

int *fibonacci__1_svc(intpair *argp, struct svc_req *rqstp) {
  int n = argp->a;
  static int result;
  printf("\n Received n: %d \n", n);
  result = calculate_fib(n);
  return (&result);
}
