/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibonacci.h"

void fibonacci_prog_1(char *host, int a) {
  CLIENT *clnt;
  int *result_1;
  intpair fibonacci__1_arg;
  clnt = clnt_create(host, FIBONACCI_PROG, FIBONACCI__VERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
  for (int i = 0; i < a; ++i) {
    fibonacci__1_arg.a = i;
    result_1 = fibonacci__1(&fibonacci__1_arg, clnt);
    if (result_1 == (int *)NULL) {
      clnt_perror(clnt, "call failed:");
    } else {
      printf("%d ", *result_1);
    }
  }
  printf("\n");
  clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
  char *host;
  int number;

  if (argc < 3) {
    printf("usage: %s <host> <n>\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  number = atoi(argv[2]);
  fibonacci_prog_1(host, number);
  exit(0);
}

