/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBONACCI_H_RPCGEN
#define _FIBONACCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
};
typedef struct intpair intpair;

#define FIBONACCI_PROG 0x23451111
#define FIBONACCI__VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIBONACCI_ 1
extern  int * fibonacci__1(intpair *, CLIENT *);
extern  int * fibonacci__1_svc(intpair *, struct svc_req *);
extern int fibonacci_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIBONACCI_ 1
extern  int * fibonacci__1();
extern  int * fibonacci__1_svc();
extern int fibonacci_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBONACCI_H_RPCGEN */
