/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"

int *prime_1_svc(intpair *argp, struct svc_req *rqstp) {
  static int result;
  int n = argp->a, flag = 0, i;
  printf("\n Received : n= %d \n", n);
  if (n == 0 || n == 1) flag = 1;
  for (i = 2; i <= n / 2; ++i) {
    if (n % i == 0) {
      flag = 1;
      break;
    }
  }
  if (!flag)
    result = 0;
  else
    result = 1;
  return (&result);
}
