/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"

void prime_prog_1(char *host, int a) {
  CLIENT *clnt;
  int *result_1;
  intpair prime_1_arg;
  clnt = clnt_create(host, PRIME_PROG, PRIME_VERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
  prime_1_arg.a = a;
  result_1 = prime_1(&prime_1_arg, clnt);
  if (result_1 == (int *)NULL) {
    clnt_perror(clnt, "call failed:");
  } else {
    if (*result_1 == 1) {
      printf("The number %d is not prime\n", a);
    } else {
      printf("The number %d is prime\n", a);
    }
  }
  clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 3) {
    printf("usage: %s <host> <number>\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  int number = atoi(argv[2]);
  prime_prog_1(host, number);
  exit(0);
}
