LIBS=-lglut -lGLU -lGL -lm

CC=g++

default: $(TARGET)

q1a:
	$(CC) ./q-01a/main.cpp $(LIBS)

q1b:
	$(CC) ./q-01b/main.cpp $(LIBS)

q1c:
	$(CC) ./q-01c/main.cpp $(LIBS)

q1d:
	$(CC) ./q-01d/main.cpp $(LIBS)

q2:
	$(CC) ./q-02/main.cpp $(LIBS)

.PHONY: clean
clean:
	rm ./a.out
