LIBS = -lglut -lGLU -lGL -lm

CC = g++

default: $(TARGET)

q1:
	g++ ./q-01/main.cpp -lglut -lGLU -lGL -lm

q2a:
	g++ ./q-02a/main.cpp -lglut -lGLU -lGL -lm

q2b:
	g++ ./q-02b/main.cpp -lglut -lGLU -lGL -lm

q3:
	g++ ./q-03/main.cpp -lglut -lGLU -lGL -lm

.PHONY: clean
clean:
	rm ./a.out
