LIBS = -lglut -lGLU -lGL -lm

CC = g++

default: $(TARGET)

q1:
	g++ ./q-01/main.cpp -lglut -lGLU -lGL -lm

q2:
	g++ ./q-02/main.cpp -lglut -lGLU -lGL -lm

q3:
	g++ ./q-03/main.cpp -lglut -lGLU -lGL -lm

q4:
	g++ ./q-04/main.cpp -lglut -lGLU -lGL -lm

q5:
	g++ ./q-05/main.cpp -lglut -lGLU -lGL -lm

.PHONY: clean
clean:
	rm ./a.out
