/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"
#include<stdlib.h>
#include<stdio.h>

float *add_1_svc(inputs *argp, struct svc_req *rqstp) {
  static float result;
  result = argp->num1 + argp->num2;
  printf("Got Request : Adding %f and %f\n", argp->num1, argp->num2);
  printf("Sent Response : %f\n", result);
  return (&result);
}

float *sub_1_svc(inputs *argp, struct svc_req *rqstp) {
  static float result;
  result = argp->num1 - argp->num2;
  printf("Got Request : Subtracting %f and %f\n", argp->num1, argp->num2);
  printf("Sent Response : %f\n", result);
  return (&result);
}

float *mul_1_svc(inputs *argp, struct svc_req *rqstp) {
  static float result;
  result = argp->num1 * argp->num2;
  printf("Got Request : Multiplying %f and %f\n", argp->num1, argp->num2);
  printf("Sent Response : %f\n", result);
  return (&result);
}

float *div_1_svc(inputs *argp, struct svc_req *rqstp) {
  static float result;
  result = argp->num1 / argp->num2;
  printf("Got Request : Dividing %f and %f\n", argp->num1, argp->num2);
  printf("Sent Response : %f\n", result);
  return (&result);
}
