/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

void calculate_prog_1(char *host, int a, int b, char c) {
  CLIENT *clnt;
  float *result_1;
  inputs add_1_arg;
  float *result_2;
  inputs sub_1_arg;
  float *result_3;
  inputs mul_1_arg;
  float *result_4;
  inputs div_1_arg;

  clnt = clnt_create(host, CALCULATE_PROG, CALCULATE_VER, "tcp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }

  if (c == '+') {
    add_1_arg.num1 = a;
    add_1_arg.num2 = b;
    result_1 = add_1(&add_1_arg, clnt);
    if (result_1 == (float *)NULL) {
      clnt_perror(clnt, "call failed");
    }
    printf("%f\n", *result_1);
  } else if (c == '-') {
    sub_1_arg.num1 = a;
    sub_1_arg.num2 = b;
    result_2 = sub_1(&sub_1_arg, clnt);
    if (result_2 == (float *)NULL) {
      clnt_perror(clnt, "call failed");
    }
    printf("%f\n", *result_2);
  } else if (c == 'x') {
    mul_1_arg.num1 = a;
    mul_1_arg.num2 = b;
    result_3 = mul_1(&mul_1_arg, clnt);
    if (result_3 == (float *)NULL) {
      clnt_perror(clnt, "call failed");
    }
    printf("%f\n", *result_3);
  } else {
    div_1_arg.num1 = a;
    div_1_arg.num2 = b;
    if (b == 0) {
      printf("Error: Cannot divide by zero\n");
    } else {
      result_4 = div_1(&div_1_arg, clnt);
      if (result_4 == (float *)NULL) {
        clnt_perror(clnt, "call failed");
      }
      printf("%f\n", *result_4);
    }
  }
  clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 5) {
    printf("usage: %s <host> <num 1> <op> <num 2>\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  float num1 = atof(argv[2]);
  char op = argv[3][0];
  float num2 = atof(argv[4]);

  calculate_prog_1(host, num1, num2, op);
  exit(0);
}
